apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app
  labels:
    app: youtube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-app
  template:
    metadata:
      labels:
        app: youtube-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: youtube-app
          image: <docker-image-name>:<tag>
          env:
           - name: DB_ROOT_PASS
             valueFrom:
               secretKeyRef:
                 name: mysql-root-password
                 key: mysql-password
           - name: DB_NAME
             value: videos
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "200m"
            requests:
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-app-service
spec:
  type: NodePort
  selector:
    app: youtube-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
