version: "3.7"

services:
  app:
    image: my_app:0.0.3
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 8082:8080
    environment:
      DB_ROOT_PASS: secret
      DB_NAME: videos
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: videos
volumes:
  mysql-data:
